export const muletillas = [
    // Generales
    "este",
    "eh",
    "o sea",
    "pues",
    "bueno",
    "digamos",
    "ya sabes",
    "como que",
    "es decir",
    "en plan",
    "así como",
    "entonces",
    "básicamente",
    "en realidad",
    "de alguna manera",
    "por así decirlo",
    "como quien dice",
    "total que",
    "nada",
    "casi que",
    "a ver",
    
    // Para ganar tiempo
    "mmm",
    "ehhh",
    "ajá",
    "bueno, pues",
    "a ver",
    "cómo te digo",
    "cómo se dice",
    "cómo se llama",
    "o algo así",
    "más o menos",
    "tal vez",
    "no sé",
    "por ejemplo",
  
    // Para reafirmar o enfatizar
    "la verdad",
    "la cosa es",
    "en serio",
    "de verdad",
    "honestamente",
    "créeme",
    "te lo digo",
    "en fin",
    "al final del día",
    "lo que pasa es que",
    "para que veas",
    "fíjate",
  
    // De transición
    "entonces",
    "por otro lado",
    "así que",
    "por lo tanto",
    "en ese sentido",
    "dicho esto",
    "en consecuencia",
    "por ende",
    "y bueno",
    "después de todo",
  
    // Redundantes (de relleno)
    "lo que pasa es que",
    "o sea, que",
    "es como",
    "¿cómo te explico?",
    "este, cómo se llama",
    "pues eso",
    "a lo que voy",
    "lo que quiero decir es",
    "básicamente eso",
  
    // Al concluir
    "en fin",
    "eso es todo",
    "pues nada",
    "así que eso",
    "y ya",
    "y pues",
    "ya está",
    "bueno, ya"
  ];
  